language: rust
rust:
  - stable
  - beta
matrix:
  fast_finish: true
  allow_failures:
    - rust: beta

before_install:
  - sudo apt-get install -y libpulse-dev libdbus-1-dev libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
script:
  - cargo build
  # - rustup component add clippy rustfmt
  # - cargo clippy --all-targets -- -D warnings
  # - cargo fmt --all -- --check
