[package]
name = "ncspot"
description = "ncurses Spotify client written in Rust using librespot, inspired by ncmpc and the likes."
exclude = ["screenshots/**"]
version = "0.1.0"
authors = ["Henrik Friedrichsen <henrik@affekt.org>"]
repository = "https://github.com/hrkfdn/ncspot"
keywords = ["spotify", "ncurses", "librespot"]
license = "BSD-2-Clause"

[badges]
travis-ci = { repository = "hrkfdn/ncspot", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
crossbeam-channel = "0.3.8"
failure = "0.1.3"
futures = "0.1"
log = "0.4.0"
serde = "1.0"
serde_json = "1.0"
toml = "0.4"
tokio = "0.1.7"
tokio-core = "0.1"
tokio-timer = "0.2"
unicode-width = "0.1.5"
dbus = { version = "0.6.4", optional = true }
xdg = "^2.1"

[dependencies.rspotify]
git = "https://github.com/hrkfdn/rspotify.git"
rev = "6029b8f50f4e5fade2ded3e3fdfe5ab8e3908450"

[dependencies.librespot]
git = "https://github.com/librespot-org/librespot.git"
rev = "daeeeaa122fc2d71edf11e562e23038db4210b39"
default-features = false

[dependencies.cursive]
version = "0.11.1"
default-features = false
features = ["pancurses-backend"]

[features]
pulseaudio_backend = ["librespot/pulseaudio-backend"]
portaudio_backend = ["librespot/portaudio-backend"]
mpris = ["dbus"]
default = ["pulseaudio_backend", "mpris"]
