[package]
name = "ncspot"
description = "ncurses Spotify client written in Rust using librespot, inspired by ncmpc and the likes."
exclude = ["screenshots/**"]
version = "0.1.0"
authors = ["Henrik Friedrichsen <henrik@affekt.org>"]
repository = "https://github.com/hrkfdn/ncspot"
keywords = ["spotify", "ncurses", "librespot"]
license = "MIT"

[badges]
travis-ci = { repository = "hrkfdn/ncspot", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
crossbeam-channel = "0.3.8"
env_logger = "0.6.0"
failure = "0.1.3"
futures = "0.1"
log = "0.4.0"
rspotify = "0.2.5"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
tokio-core = "0.1"
tokio-timer = "0.2"
unicode-width = "0.1.5"

[dependencies.librespot]
git = "https://github.com/librespot-org/librespot.git"
rev = "daeeeaa122fc2d71edf11e562e23038db4210b39"
default-features = false

[dependencies.cursive]
git = "https://github.com/gyscos/Cursive.git"
default-features = false
features = ["pancurses-backend"]

[features]
pulseaudio_backend = ["librespot/pulseaudio-backend"]
portaudio_backend = ["librespot/portaudio-backend"]
default = ["pulseaudio_backend"]
