name: CD

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    name: Publishing Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout src
      - name: Running cargo build
        run: cargo build --no-default-features --features rodio_backend,cursive/pancurses-backend --release
      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/ncspot.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
